title: To Illustrate Illustrious Virtue
author: Michael
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I've been having all sorts of thoughts about the theory and craft of beauty. 
  I've written them down as personal notes, but now I would like to try presenting
  them to my friends and colleagues. Welcome to my blog!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
